services:
  ui-cars:
    build:
      dockerfile: Dockerfile
      context: './gpds-ui'
    ports:
      - "8082:80"
    networks:
      - gpds-network

  api-cars:
    build:
      dockerfile: Dockerfile
      context: './gpds-autos'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/autos10a
      SPRING_DATASOURCE_USERNAME: autos
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: roopassword
      MYSQL_DATABASE: autos10a
      MYSQL_USER: autos
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
networks:
  gpds-network:
    driver: bridge
