services:
  ui-cars:
    build:
      context: './gpds-ui'
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      - gpds-network
    depends_on:
      - api-cars
  api-cars:
    build:
      context: './gpds-autos'
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - gpds-network
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: roopassword
      MYSQL_DATABASE: autos10a
      MYSQL_USER: autos
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - gpds-network

networks:
  gpds-network:
    driver: bridge
